version: '3.4'

services:
  xplatsolutions.partycraft.authorizationservice:
    image: ${DOCKER_REGISTRY-}xplatsolutionspartycraftauthorizationservice
    build:
      context: .
      dockerfile: XPlatSolutions.PartyCraft.AuthorizationService/Dockerfile
    networks:
      - main_network    
    links:
      - "mongo:mongolocal"
    depends_on:
      - mongo
    environment:
      - "Options__ConnectionString=mongodb://admin:XPlatQwerty12@mongo:27017" #TODO
      - "Options__HostName=rabbitmqspam"
      - "Options__UserName=admin"
      - "Options__PasswordRmq=XPlatQwerty12"
      - "Options__AnalyticsHostName=rabbitmqanalytics"
      - "Options__AnalyticsUserName=admin"
      - "Options__AnalyticsPasswordRmq=XPlatQwerty12"

  mongo:
    container_name: "mongolocal"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: XPlatQwerty12  
    networks:
      - main_network
    ports:
      - '27018:27018'

#networks:
#    authnetwork:
#      driver: bridge

networks:
   main_network:
     external: true